export declare type MdbSmoothScrollEasingFunction = (t: number) => number;
export declare type MdbSmoothScrollEasing = 'linear' | 'easeInQuad' | 'easeInCubic' | 'easeInQuart' | 'easeInQuint' | 'easeInOutQuad' | 'easeInOutCubic' | 'easeInOutQuard' | 'easeInOutQuint' | 'easeOutQuad' | 'easeOutCubic' | 'easeOutQuard' | 'easeOutQuint';
export declare const easingFunctions: {
    linear: typeof linear;
    easeInQuad: typeof easeInQuad;
    easeInCubic: typeof easeInCubic;
    easeInQuart: typeof easeInQuart;
    easeInQuint: typeof easeInQuint;
    easeInOutQuad: typeof easeInOutQuad;
    easeInOutCubic: typeof easeInOutCubic;
    easeInOutQuart: typeof easeInOutQuart;
    easeInOutQuint: typeof easeInOutQuint;
    easeOutQuad: typeof easeOutQuad;
    easeOutCubic: typeof easeOutCubic;
    easeOutQuart: typeof easeOutQuart;
    easeOutQuint: typeof easeOutQuint;
};
declare function linear(t: number): number;
declare function easeInQuad(t: number): number;
declare function easeInCubic(t: number): number;
declare function easeInQuart(t: number): number;
declare function easeInQuint(t: number): number;
declare function easeInOutQuad(t: number): number;
declare function easeInOutCubic(t: number): number;
declare function easeInOutQuart(t: number): number;
declare function easeInOutQuint(t: number): number;
declare function easeOutQuad(t: number): number;
declare function easeOutCubic(t: number): number;
declare function easeOutQuart(t: number): number;
declare function easeOutQuint(t: number): number;
export {};
