export declare function getDate(date: Date): number;
export declare function getDayNumber(date: Date): number;
export declare function getMonth(date: Date): number;
export declare function getYear(date: Date): number;
export declare function getFirstDayOfWeek(year: number, month: number, startDay: number): number;
export declare function getDaysInMonth(date: Date): number;
export declare function getMonthEnd(date: Date): Date;
export declare function getToday(): Date;
export declare function addYears(date: Date, years: number): Date;
export declare function addMonths(date: Date, months: number): Date;
export declare function addDays(date: Date, days: number): Date;
export declare function createDate(year: number, month: number, day: number): Date;
export declare function convertStringToDate(dateString: string): Date;
export declare function isValidDate(date: Date): boolean;
export declare function compareDates(date1: Date, date2: Date): number;
export declare function isSameDate(date1: Date, date2: Date): boolean;
export declare function getYearsOffset(activeDate: Date, yearsInView: number, minDate: Date, maxDate: Date): number;
export declare function getStartYear(yearsInView: number, minDate: Date, maxDate: Date): number;
export declare function isDateDisabled(date: Date, minDate: Date, maxDate: Date, filter: any): boolean;
export declare function isMonthDisabled(month: number, year: number, minDate: Date, maxDate: Date): boolean;
export declare function isYearDisabled(year: number, minDate: Date, maxDate: Date): boolean;
export declare function isNextDateDisabled(activeDate: Date, view: string, yearsInView: number, minDate: Date, maxDate: Date): boolean;
export declare function isPreviousDateDisabled(activeDate: Date, view: string, yearsInView: number, minDate: Date, maxDate: Date): boolean;
export declare function areDatesInSameView(date1: Date, date2: Date, view: string, yearsInView: number, minDate: Date, maxDate: Date): boolean;
