import { BooleanInput } from '@angular/cdk/coercion';
import { TemplatePortal } from '@angular/cdk/portal';
import { TemplateRef, ElementRef, OnChanges, SimpleChanges, ViewContainerRef, AfterContentInit } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { Subject } from 'rxjs';
import * as i0 from "@angular/core";
export declare class MdbStepComponent implements OnChanges, AfterContentInit {
    el: ElementRef;
    private _vcr;
    _icon: TemplateRef<any>;
    content: TemplateRef<any>;
    get editable(): boolean;
    set editable(value: boolean);
    private _editable;
    name: string;
    label: string;
    get optional(): boolean;
    set optional(value: boolean);
    private _optional;
    stepForm: FormGroup;
    _onChanges: Subject<void>;
    constructor(el: ElementRef, _vcr: ViewContainerRef);
    get isCompleted(): boolean;
    set isCompleted(value: boolean);
    private _isCompleted;
    get isInvalid(): boolean;
    set isInvalid(value: boolean);
    private _isInvalid;
    get isActive(): boolean;
    set isActive(value: boolean);
    private _isActive;
    get icon(): TemplatePortal | null;
    private _iconPortal;
    private _removeClasses;
    reset(): void;
    ngAfterContentInit(): void;
    ngOnChanges(changes: SimpleChanges): void;
    private _createIconPortal;
    static ngAcceptInputType_editable: BooleanInput;
    static ngAcceptInputType_optional: BooleanInput;
    static ɵfac: i0.ɵɵFactoryDeclaration<MdbStepComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<MdbStepComponent, "mdb-step", ["mdbStep"], { "editable": "editable"; "name": "name"; "label": "label"; "optional": "optional"; "stepForm": "stepForm"; }, {}, ["_icon"], ["*"]>;
}
