import { QueryList, AfterContentInit, ElementRef, EventEmitter, OnDestroy, ChangeDetectorRef } from '@angular/core';
import { MdbStepComponent } from './step.component';
import { BooleanInput } from '@angular/cdk/coercion';
import * as i0 from "@angular/core";
export declare type MdbStepperOrientation = 'horizontal' | 'vertical';
export interface MdbStepChangeEvent {
    activeStep: MdbStepComponent;
    activeStepIndex: number;
    previousStep: MdbStepComponent;
    previousStepIndex: number;
}
export declare class MdbStepperComponent implements AfterContentInit, OnDestroy {
    private _cdRef;
    steps: QueryList<MdbStepComponent>;
    stepTitles: QueryList<ElementRef>;
    stepContents: QueryList<ElementRef>;
    container: ElementRef;
    orientation: MdbStepperOrientation;
    get linear(): boolean;
    set linear(value: boolean);
    private _linear;
    get stepperHeadClick(): boolean;
    set stepperHeadClick(value: boolean);
    private _stepperHeadClick;
    get mobile(): boolean;
    set mobile(value: boolean);
    private _mobile;
    mobileBarBreakpoint: number;
    get stepperMobileStepTxt(): string;
    set stepperMobileStepTxt(value: string);
    private _stepperMobileStepTxt;
    get stepperMobileBackBtn(): string;
    set stepperMobileBackBtn(value: string);
    private _stepperMobileBackBtn;
    get stepperMobileNextBtn(): string;
    set stepperMobileNextBtn(value: string);
    private _stepperMobileNextBtn;
    get stepperMobileOfTxt(): string;
    set stepperMobileOfTxt(value: string);
    private _stepperMobileOfTxt;
    get markAsCompleted(): boolean;
    set markAsCompleted(value: boolean);
    private _markAsCompleted;
    stepChange: EventEmitter<MdbStepChangeEvent>;
    constructor(_cdRef: ChangeDetectorRef);
    private _destroy;
    private _activeStepIndex;
    private _activeStep;
    get allStepsNumber(): number;
    getProgressBarWidth(): number;
    get activeStepIndex(): number;
    set activeStepIndex(value: number);
    private _isStepValid;
    getAnimationState(index: number): string;
    private _getStepByIndex;
    next(): void;
    previous(): void;
    submit(): void;
    handleHeaderClick(index: number): void;
    setNewActiveStep(index: number): void;
    private _markCurrentAsDone;
    private _markCurrentAsWrong;
    private _markStepControlsAsDirty;
    private _removeStepValidationClasses;
    private _isNewStepLinear;
    private _setActiveStep;
    private _removeCurrentActiveStep;
    resetAll(): void;
    ngAfterContentInit(): void;
    ngOnDestroy(): void;
    static ngAcceptInputType_linear: BooleanInput;
    static ngAcceptInputType_mobile: BooleanInput;
    static ngAcceptInputType_markAsCompleted: BooleanInput;
    static ɵfac: i0.ɵɵFactoryDeclaration<MdbStepperComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<MdbStepperComponent, "mdb-stepper", ["mdbStepper"], { "orientation": "orientation"; "linear": "linear"; "stepperHeadClick": "stepperHeadClick"; "mobile": "mobile"; "mobileBarBreakpoint": "mobileBarBreakpoint"; "stepperMobileStepTxt": "stepperMobileStepTxt"; "stepperMobileBackBtn": "stepperMobileBackBtn"; "stepperMobileNextBtn": "stepperMobileNextBtn"; "stepperMobileOfTxt": "stepperMobileOfTxt"; "markAsCompleted": "markAsCompleted"; }, { "stepChange": "stepChange"; }, ["steps"], never>;
}
